// <auto-generated />
using System;
using CoreLedger.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CoreLedger.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CoreLedgerDbContext))]
    [Migration("20260924124517_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pgcrypto");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CoreLedger.Domain.Entities.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasMaxLength(34)
                        .HasColumnType("character varying(34)")
                        .HasColumnName("account_number");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_user_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_accounts");

                    b.HasIndex("AccountNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_accounts_account_number");

                    b.HasIndex("OwnerUserId")
                        .HasDatabaseName("ix_accounts_owner_user_id");

                    b.ToTable("accounts", (string)null);
                });

            modelBuilder.Entity("CoreLedger.Domain.Entities.BalanceSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<Guid?>("LastLedgerEntryId")
                        .HasColumnType("uuid")
                        .HasColumnName("last_ledger_entry_id");

                    b.Property<DateTimeOffset>("SnapshotAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("snapshot_at")
                        .HasDefaultValueSql("now()");

                    b.Property<decimal>("SnapshotBalance")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("snapshot_balance");

                    b.HasKey("Id")
                        .HasName("pk_balance_snapshots");

                    b.HasIndex("LastLedgerEntryId")
                        .HasDatabaseName("ix_balance_snapshots_last_ledger_entry_id");

                    b.HasIndex("AccountId", "SnapshotAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_balance_snapshots_account_id_snapshot_at");

                    b.ToTable("balance_snapshots", (string)null);
                });

            modelBuilder.Entity("CoreLedger.Domain.Entities.IdempotencyLog", b =>
                {
                    b.Property<Guid>("IdempotencyKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("idempotency_key");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("RequestHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("request_hash");

                    b.Property<string>("ResponseBody")
                        .HasColumnType("jsonb")
                        .HasColumnName("response_body");

                    b.Property<int?>("ResponseStatusCode")
                        .HasColumnType("integer")
                        .HasColumnName("response_status_code");

                    b.HasKey("IdempotencyKey")
                        .HasName("pk_idempotency_logs");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_idempotency_logs_expires_at");

                    b.ToTable("idempotency_logs", (string)null);
                });

            modelBuilder.Entity("CoreLedger.Domain.Entities.LedgerEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("amount");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("direction");

                    b.Property<Guid>("TransactionId")
                        .HasColumnType("uuid")
                        .HasColumnName("transaction_id");

                    b.HasKey("Id")
                        .HasName("pk_ledger_entries");

                    b.HasIndex("TransactionId")
                        .HasDatabaseName("ix_ledger_entries_transaction_id");

                    b.HasIndex("AccountId", "CreatedAt")
                        .HasDatabaseName("ix_ledger_entries_account_id_created_at");

                    b.ToTable("ledger_entries", null, t =>
                        {
                            t.HasCheckConstraint("CK_LedgerEntries_Amount_Positive", "amount > 0");

                            t.HasCheckConstraint("CK_LedgerEntries_Direction", "direction IN ('Debit', 'Credit')");
                        });
                });

            modelBuilder.Entity("CoreLedger.Domain.Entities.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTimeOffset?>("FraudCheckedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fraud_checked_at");

                    b.Property<decimal?>("FraudScore")
                        .HasColumnType("numeric(4,3)")
                        .HasColumnName("fraud_score");

                    b.Property<DateTimeOffset>("InitiatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("initiated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Pending")
                        .HasColumnName("status");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_transactions");

                    b.ToTable("transactions", null, t =>
                        {
                            t.HasCheckConstraint("CK_Transactions_Status", "status IN ('Pending', 'Completed', 'Failed', 'Blocked')");

                            t.HasCheckConstraint("CK_Transactions_Type", "type IN ('Transfer', 'Deposit', 'Withdrawal')");
                        });
                });

            modelBuilder.Entity("CoreLedger.Domain.Entities.BalanceSnapshot", b =>
                {
                    b.HasOne("CoreLedger.Domain.Entities.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_balance_snapshots_accounts_account_id");

                    b.HasOne("CoreLedger.Domain.Entities.LedgerEntry", null)
                        .WithMany()
                        .HasForeignKey("LastLedgerEntryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_balance_snapshots_ledger_entries_last_ledger_entry_id");

                    b.Navigation("Account");
                });

            modelBuilder.Entity("CoreLedger.Domain.Entities.LedgerEntry", b =>
                {
                    b.HasOne("CoreLedger.Domain.Entities.Account", "Account")
                        .WithMany("LedgerEntries")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_ledger_entries_accounts_account_id");

                    b.HasOne("CoreLedger.Domain.Entities.Transaction", "Transaction")
                        .WithMany("LedgerEntries")
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_ledger_entries_transactions_transaction_id");

                    b.Navigation("Account");

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("CoreLedger.Domain.Entities.Account", b =>
                {
                    b.Navigation("LedgerEntries");
                });

            modelBuilder.Entity("CoreLedger.Domain.Entities.Transaction", b =>
                {
                    b.Navigation("LedgerEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
